# Generated by Django 5.0.4 on 2024-04-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plays', models.JSONField()),
                ('rtp', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
